version: '3'
services:
  dbos:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass 
      MYSQL_USER: rithwik
      MYSQL_PASSWORD: qwerty 
      MYSQL_DATABASE: sqldb


  wpos:
    image: wordpress:5.1.1-php7.3-apache       
    restart: always
    depends_on:
      - dbos
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: dbos 
      WORDPRESS_DB_USER: rithwik 
      WORDPRESS_DB_PASSWORD: qwerty 
      WORDPRESS_DB_NAME: sqldb
